# Generated by Django 3.1.6 on 2021-03-05 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiaccess', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccessTokens',
            new_name='AccessToken',
        ),
    ]
