# Generated by Django 3.1.6 on 2021-03-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiaccess', '0002_auto_20210305_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoken',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
