# Generated by Django 3.1.1 on 2020-09-23 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemfinder', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mail',
            new_name='Leather',
        ),
    ]
