# Generated by Django 3.1.1 on 2020-09-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemfinder', '0002_auto_20200924_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leather',
            name='slot',
            field=models.CharField(choices=[('Head', 'Head'), ('Shoulder', 'Shoulder'), ('Back', 'Back'), ('Chest', 'Chest'), ('Wrist', 'Wrist'), ('Hands', 'Hands'), ('Waist', 'Waist'), ('Legs', 'Legs'), ('Feet', 'Feet')], max_length=10),
        ),
    ]
