# Generated by Django 3.1.1 on 2020-09-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemfinder', '0004_cloth_mail_plate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('Neck', 'Neck'), ('Finger', 'Finger')], max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('source', models.CharField(choices=[('Raid', 'Raid'), ('Dungeon', 'Dungeon')], max_length=7)),
                ('source_name', models.CharField(max_length=25)),
                ('haste', models.IntegerField()),
                ('crit', models.IntegerField()),
                ('vers', models.IntegerField()),
                ('mastery', models.IntegerField()),
                ('image_url', models.CharField(max_length=250)),
                ('wowhead_url', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Trinkets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('source', models.CharField(choices=[('Raid', 'Raid'), ('Dungeon', 'Dungeon')], max_length=7)),
                ('source_name', models.CharField(max_length=25)),
                ('spec', models.CharField(choices=[('Heal', 'Heal'), ('Tank', 'Tank'), ('Caster', 'Caster'), ('Melee', 'Melee')], max_length=10)),
                ('image_url', models.CharField(max_length=250)),
                ('wowhead_url', models.CharField(max_length=250)),
            ],
        ),
    ]
