# Generated by Django 3.1.1 on 2020-09-25 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemfinder', '0005_others_trinkets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Others',
            new_name='Other',
        ),
        migrations.RenameModel(
            old_name='Trinkets',
            new_name='Trinket',
        ),
    ]
