# Generated by Django 3.1.1 on 2020-09-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemfinder', '0006_auto_20200925_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='agility',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='strength',
            field=models.BooleanField(default=False),
        ),
    ]
