# Generated by Django 3.1.1 on 2021-02-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itemfinder', '0009_auto_20201016_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='slot',
            field=models.CharField(choices=[('Head', 'Head'), ('Shoulder', 'Shoulder'), ('Chest', 'Chest'), ('Wrist', 'Wrist'), ('Hands', 'Hands'), ('Waist', 'Waist'), ('Legs', 'Legs'), ('Feet', 'Feet')], max_length=10),
        ),
        migrations.AlterField(
            model_name='leather',
            name='slot',
            field=models.CharField(choices=[('Head', 'Head'), ('Shoulder', 'Shoulder'), ('Chest', 'Chest'), ('Wrist', 'Wrist'), ('Hands', 'Hands'), ('Waist', 'Waist'), ('Legs', 'Legs'), ('Feet', 'Feet')], max_length=10),
        ),
        migrations.AlterField(
            model_name='mail',
            name='slot',
            field=models.CharField(choices=[('Head', 'Head'), ('Shoulder', 'Shoulder'), ('Chest', 'Chest'), ('Wrist', 'Wrist'), ('Hands', 'Hands'), ('Waist', 'Waist'), ('Legs', 'Legs'), ('Feet', 'Feet')], max_length=10),
        ),
        migrations.AlterField(
            model_name='other',
            name='slot',
            field=models.CharField(choices=[('Neck', 'Neck'), ('Finger', 'Finger'), ('Back', 'Back')], max_length=10),
        ),
        migrations.AlterField(
            model_name='plate',
            name='slot',
            field=models.CharField(choices=[('Head', 'Head'), ('Shoulder', 'Shoulder'), ('Chest', 'Chest'), ('Wrist', 'Wrist'), ('Hands', 'Hands'), ('Waist', 'Waist'), ('Legs', 'Legs'), ('Feet', 'Feet')], max_length=10),
        ),
    ]
